name: Validate

on: [push, pull_request]

jobs:
  skip_check:
    name: Check concurrent runs
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip}}
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        id: skip_check
        with:
          concurrent_skipping: same_content_newer
          cancel_others: true
          skip_after_successful_duplicate: false

  deps:
    name: Prepare deps cache
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Prime pnpm store cache
        run: pnpm fetch

  build:
    name: Build
    needs: [skip_check, deps]
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Deps (offline)
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Check Nextjs Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build
        run: pnpm build

  lint:
    name: Lint
    needs: [skip_check, deps]
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Deps (offline)
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Lint
        run: pnpm lint
