name: Validate

on: [push, pull_request]

jobs:
  skip_check:
    name: Check concurrent runs
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip}}
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        id: skip_check
        with:
          concurrent_skipping: same_content_newer
          cancel_other: true
          skip_after_successful_duplicate: false
  test:
    name: Lint & Test
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - id: pnpm-setup
        uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint
